# Generated by Django 5.2.2 on 2025-06-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_campaign_amount_pledged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_pledged',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
